### ISSUE TITLE
[question] Não foi pra frente?

### ISSUE THREAD

**Issue by lricoy** [brunopulis/feedback#2]
A ideia parece bacana. Talvez algo mais automatizado que mostre quem dá feedback e quem não usando reações as issues.

**Comment by brunopulis** [comment]
@lricoy Sua ideia é interessante, mas eu pretendendo desenvolver uma SPA mesmo onde as pessoas poderão incluir as empresas de modo anônimo, caso queira me ajudar nessa empreitada ai será muito bem vindo! :)

**Comment by lricoy** [comment]
Claro :)

Se tiver um Trello ou algo pode me colocar. Batemos um papo qualquer dia
para planejar :)

Em Sex, 14 de jul de 2017 21:33, Bruno Pulis <notifications@github.com>
escreveu:

**Comment by brunopulis** [comment]
@lricoy Vou usar o Project do Github mesmo.
