### ISSUE TITLE
Configuração do Repositório

### ISSUE THREAD

**Issue by brunopulis** [brunopulis/feedback#6]
- [x] Ajustar Travis
- [x] Ajustar package.json
- [x] Ajustar Readme
- [x] Traduzir o CONTRIBUTING para pt-br

**Comment by mvfsillva** [comment]
@brunopulis o que acha de colocar tudo em EN?

**Comment by brunopulis** [comment]
@mvfsillva Colocar o repositório por completo em EN? Se for, não vejo problemas quanto a isso.
